modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="window_breaker"
version="0.1.0"
displayName="Window Breaker"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="\u6E05\u7FBDLE/Qingyu_ch,MCreator"
description="The Window-Breaker"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.window_breaker]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

# End of user code block dependencies configuration
